# Generated by Django 2.2.1 on 2019-05-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_name_id', models.CharField(max_length=20, unique=True)),
                ('primary_name', models.CharField(max_length=120)),
                ('birth_year', models.IntegerField(blank=True)),
                ('death_year', models.IntegerField(blank=True)),
                ('primary_profession', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('imdb_name_id',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_title_id', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=120)),
                ('primary_title', models.CharField(max_length=200)),
                ('original_title', models.CharField(max_length=200)),
                ('is_adult', models.BooleanField()),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True)),
                ('runtime_minutes', models.IntegerField(blank=True)),
                ('genres', models.CharField(max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Name')),
            ],
            options={
                'ordering': ('imdb_title_id',),
            },
        ),
    ]
