# Generated by Django 2.2.1 on 2019-05-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='death_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
