# Generated by Django 2.2.1 on 2019-05-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190513_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='runtime_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
