# Generated by Django 2.2.1 on 2019-05-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190513_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Name'),
        ),
    ]
